name: van_inventory
description: "Van Inventory – Lager, Kunden/Aufmaß, Export, optional mit Firebase-Sync"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Lokale Persistenz / Utils
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3
  share_plus: ^10.1.4
  intl: ^0.19.0

  # Optional: Firebase (Auth + Firestore), wird nur benutzt wenn BACKEND=firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.17.5

  # UI
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
