// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_LeXgch_Pm63UfXmY4IYIIugT5Rp2qJc',
    appId: '1:712505442928:web:ec0d373fc2892243d76ab5',
    messagingSenderId: '712505442928',
    projectId: 'van-inventory-16f99',
    authDomain: 'van-inventory-16f99.firebaseapp.com',
    storageBucket: 'van-inventory-16f99.firebasestorage.app',
    measurementId: 'G-4GT5QE3RMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx8l1dK-IXf1BwxdIS_SdyoV6E-rOFNlA',
    appId: '1:712505442928:android:26c563916a02db7cd76ab5',
    messagingSenderId: '712505442928',
    projectId: 'van-inventory-16f99',
    storageBucket: 'van-inventory-16f99.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-_qi4gBAYbpez-gNr5qhuQiCDqFRRzBw',
    appId: '1:712505442928:ios:55edb3ff3332f5d2d76ab5',
    messagingSenderId: '712505442928',
    projectId: 'van-inventory-16f99',
    storageBucket: 'van-inventory-16f99.firebasestorage.app',
    iosBundleId: 'com.example.vanInventory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-_qi4gBAYbpez-gNr5qhuQiCDqFRRzBw',
    appId: '1:712505442928:ios:55edb3ff3332f5d2d76ab5',
    messagingSenderId: '712505442928',
    projectId: 'van-inventory-16f99',
    storageBucket: 'van-inventory-16f99.firebasestorage.app',
    iosBundleId: 'com.example.vanInventory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_LeXgch_Pm63UfXmY4IYIIugT5Rp2qJc',
    appId: '1:712505442928:web:30af4618d4cf0066d76ab5',
    messagingSenderId: '712505442928',
    projectId: 'van-inventory-16f99',
    authDomain: 'van-inventory-16f99.firebaseapp.com',
    storageBucket: 'van-inventory-16f99.firebasestorage.app',
    measurementId: 'G-2W1Q00P49G',
  );
}
